#include "arduino_secrets.h"

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/3bd7c5c8-bc1a-4452-b5a3-0ffb0d355302 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight light1;
  CloudLight light2;
  CloudLight light3;
  CloudLight light4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  Serial.begin(9600,SERIAL_8N1);
  pinMode(2,OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information youâll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since Light1 is READ_WRITE variable, onLight1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight1Change()  {
  if(light1==1)
  {
    Serial.print("light1on");
    //digitalWrite(2,LOW);
  }
  else
  {
    Serial.print("light1off");
    //digitalWrite(2,HIGH);    
  }
  // Add your code here to act upon Light1 change
}

/*
  Since Light2 is READ_WRITE variable, onLight2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight2Change()  {
  if(light2==1)
  {
    Serial.print("light2on");
  }
  else
  {
    Serial.print("light2off");    
  }
  // Add your code here to act upon Light2 change
}

/*
  Since Light3 is READ_WRITE variable, onLight3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight3Change()  {
  if(light3==1)
  {
    Serial.print("light3on");
  }
  else
  {
    Serial.print("light3off");    
  }
  // Add your code here to act upon Light3 change
}

/*
  Since Light4 is READ_WRITE variable, onLight4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight4Change()  {
  if(light4==1)
  {
    Serial.print("light4on");
  }
  else
  {
    Serial.print("light4off");    
  }
  // Add your code here to act upon Light4 change
}